version: "3.7"
services:
  postgres:
    image: postgres:latest
    container_name: test_postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
    restart: always
  # APP*****************************************
  app:
    build: .
    container_name: yellow_app
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
    restart: always

volumes:
  db-data: